field: 6a3c9bb0-dff3-4b71-933d-0cdf1099a0a4
fieldLayouts:
  c9d7d48b-3816-495a-b706-360604b3e532:
    tabs:
      -
        elements:
          -
            fieldUid: 368c04ff-100f-4619-8b5f-7d76a65af587
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  368c04ff-100f-4619-8b5f-7d76a65af587:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:09334a47-33fa-4e9e-8f7d-7a5ef88dedf7'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:09334a47-33fa-4e9e-8f7d-7a5ef88dedf7'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
